"""create tables for models

Revision ID: 5d8abdae0e1d
Revises: 0a1b2c3d4e5f
Create Date: 2025-11-09 12:21:12.504872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8abdae0e1d'
down_revision = '0a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mailer'
    )
    op.create_index(op.f('ix_mailer_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True, schema='mailer')
    op.create_table('daily_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['mailer.api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'day', name='uq_daily_usage_api_key_day'),
    schema='mailer'
    )
    op.create_index(op.f('ix_mailer_daily_usage_api_key_id'), 'daily_usage', ['api_key_id'], unique=False, schema='mailer')
    op.create_table('send_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['mailer.api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mailer'
    )
    op.create_index(op.f('ix_mailer_send_logs_api_key_id'), 'send_logs', ['api_key_id'], unique=False, schema='mailer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailer_send_logs_api_key_id'), table_name='send_logs', schema='mailer')
    op.drop_table('send_logs', schema='mailer')
    op.drop_index(op.f('ix_mailer_daily_usage_api_key_id'), table_name='daily_usage', schema='mailer')
    op.drop_table('daily_usage', schema='mailer')
    op.drop_index(op.f('ix_mailer_api_keys_key_hash'), table_name='api_keys', schema='mailer')
    op.drop_table('api_keys', schema='mailer')
    # ### end Alembic commands ###