"""empty message

Revision ID: 3a6d49148851
Revises: 5d8abdae0e1d
Create Date: 2025-11-09 16:10:11.677707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a6d49148851'
down_revision = '5d8abdae0e1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('allowed_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='mailer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'allowed_recipients', schema='mailer')
    # ### end Alembic commands ###